USE master;
GO

CREATE ENDPOINT MirroringEndpoint
STATE = STARTED
AS TCP (LISTENER_PORT = 5022)
FOR DATABASE_MIRRORING
(
    ROLE = PARTNER,
    AUTHENTICATION = WINDOWS NEGOTIATE,
    ENCRYPTION = REQUIRED ALGORITHM AES
);
GO

ALTER DATABASE AdventureWorksLT2022
SET PARTNER = 'TCP://MIRROR_SERVER_NAME:5022';
GO

/*
Sunucu adlarını kendi ortamınıza göre değiştirin.
*/
