USE master;
GO

RESTORE DATABASE AdventureWorksLT2022
FROM DISK = 'C:\SQLBackups\AdventureWorksLT2022\Full\AdventureWorksLT2022_FULL.bak'
WITH NORECOVERY, REPLACE;
GO

RESTORE LOG AdventureWorksLT2022
FROM DISK = 'C:\SQLBackups\AdventureWorksLT2022\Log\AdventureWorksLT2022_LOG_001.trn'
WITH NORECOVERY;
GO

CREATE ENDPOINT MirroringEndpoint
STATE = STARTED
AS TCP (LISTENER_PORT = 5022)
FOR DATABASE_MIRRORING
(
    ROLE = PARTNER,
    AUTHENTICATION = WINDOWS NEGOTIATE,
    ENCRYPTION = REQUIRED ALGORITHM AES
);
GO

ALTER DATABASE AdventureWorksLT2022
SET PARTNER = 'TCP://PRINCIPAL_SERVER_NAME:5022';
GO
